# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"download_video": "00_dataset.ipynb",
         "print_progress": "00_dataset.ipynb",
         "extract_frames": "00_dataset.ipynb",
         "video_to_frames": "00_dataset.ipynb",
         "video_url_to_frames": "00_dataset.ipynb"}

modules = ["dataset.py"]

doc_url = "https://spiyer99.github.io/video_remaster/"

git_url = "https://github.com/spiyer99/video_remaster/tree/{branch}/"

def custom_doc_links(name): return None
